### ISSUE TITLE
Enhancement requests: Search box, Sorting

### ISSUE THREAD

**Issue by ardissaps** [magicus/ModSettings#10]
Suggestion :
- Searchbox
- Sort option (date installed, last opened, alphabet)

Thank you

**Comment by magicus** [comment]
This is a bug report (for Puzzle mod) and two feature requests, all baked in one. In the future, when reporting issues, please create separate reports for separate questions.

**Comment by magicus** [comment]
The problem with Puzzle mod is most likely with the mod itself. My guess is that it is bundling separate mods which all have the same configuration screen. 

Is it this mod: https://www.curseforge.com/minecraft/mc-mods/puzzle ?

**Comment by magicus** [comment]
I have split this bug report into two, keeping this one about the feature requests and opening #12 to handle the issue with Puzzle.

**Comment by magicus** [comment]
Search box added in 2.0.0. 

I did not implement a way to change sort order. There is no way to get date installed for a mod from Fabric what I could find. Tracking last time the setting screen where opened would require adding a lot of complexity.
