### ISSUE TITLE
When will there be an update for 1.19.4?

### ISSUE THREAD

**Issue by MetricsLite** [magicus/ModSettings#17]
When will there be an update for 1.19.4?

**Comment by magicus** [comment]
1.19.4 radically changed how the in-game pause menu is rendered (again...), so it will unfortunately require a more or less total rewrite of the core logic of this mod. 

I'll try to get some spare time for it, but can't promise any ETA.

**Comment by magicus** [comment]
1.19.4 support is now released. Sorry for the huge delay...
