### ISSUE TITLE
[suggestion] keybind to open ModSettings screen

### ISSUE THREAD

**Issue by yesn0t** [magicus/ModSettings#3]
hello, thank you for making this mod, it has quickly become a must-have :D
may i suggest adding a keybind to open modsettings ? many mods offer a keybind to open their respective configuration screens, but i find that incovenient because it requires way too many keybinds. Instead with modsettings, they could all be under one keybind x)

**Comment by magicus** [comment]
Good idea! I'll see what I can do. :)
