### ISSUE TITLE
Crash when other mods bundle old ModMenu API

### ISSUE THREAD

**Issue by the-unheard** [magicus/ModSettings#4]
https://crashy.net/uI2vk4lXteRgw989AFKW

**Comment by magicus** [comment]
```
Caused by: java.lang.NoClassDefFoundError: io/github/prospector/modmenu/api/ModMenuApi

```

This is a bit odd, since the 1.18.1 version should have no more references to the old `io.github.prospector` API...

**Comment by magicus** [comment]
@the-unheard Can you reproduce the crash with fewer mods installed? I'm guessing some other mod might bundle a bad version of the Mod Menu API.

If you only install ModSettings, or only install ModSettings and Mod Menu -- does it still crash?

**Comment by 2020Sanoj** [comment]
I can confirm the Crash with the following Mods, every Mod + Fabric + Minecraft latest version:

- https://www.curseforge.com/minecraft/mc-mods/capes
- https://www.curseforge.com/minecraft/mc-mods/eggtab-fabric
- https://www.curseforge.com/minecraft/mc-mods/enhanced-attack-indicator
- https://www.curseforge.com/minecraft/mc-mods/auto-config-updated-api

They all use Auto Config Updated API (the one Mod is it), which uses in the newest version the old Mod Menu API, on their GitHub Repo it is already fixed (https://github.com/shedaniel/AutoConfig/pull/32/files)

**Comment by magicus** [comment]
Ok, so even though the old API is deprecated, some mods still use it, and this causes a crash. I could change Mod Settings to just not crash, but that seems pointless, so I have restored support for the old API. Guess we'll actually be stuck with it forever...
