### ISSUE TITLE
Incompatible with Minimal Menu

### ISSUE THREAD

**Issue by 2020Sanoj** [magicus/ModSettings#5]
![image](https://user-images.githubusercontent.com/75573284/150574340-5f0040cf-c608-48bc-9c52-a84c3661b95e.png)

When I remove the Minimal Menu Mod (https://www.curseforge.com/minecraft/mc-mods/minimal-menu) or the Mod settings Mod, the main menu looks normal, so I think the Mod settings Mod and the Minimal Menu Mod are incompatible

**Comment by magicus** [comment]
It is likely that they just are incompatible. Having multiple mods modifying the main menu is conflict prone. With that said, I'll have a look at Minimal Menu to see if there's anything I can do to improve interaction.

**Comment by JustAnOkapi** [comment]
I have the same problem and it seems to also be the same two mods

**Comment by magicus** [comment]
@2020Sanoj What solution would you expect/prefer when combining Minimal Menu (which removes menu buttons) and Mod Settings (which adds butttons)? If you get one wide "Mod Settings" button at the end of the list, would that be acceptable?

**Comment by 2020Sanoj** [comment]
I accept any solution, as log as the main screen don't have buttons duplicated or on random positions. So do that what the easiest option for you is.

**Comment by yesn0t** [comment]
just wanted to say that i use both mods on 1.17.1 and they work well together,  
`modsettings 1.0.0` and `minimalmenu 0.0.7`  
potentially noteworthy : 0.0.7 was the last minimalmenu version for 1.17 and it didn't use cloth config, so i suppose major changes happened between that and current 1.0+ versions of minimalmenu

**Comment by magicus** [comment]
I think I have a solution to this now. It fixes all apparent problems, anyway. But the test matrix is large with all possible adjustments in Minimal Menu, cmobined with how Mod Menu can be instructed to place its "Mods" button, so it will not look nice in all combinations. (Not just my fault; try Mod Menu "adjacent" placement, combined with "Remove Realms" in "Minimal Menu" ... *ugh*)
