### ISSUE TITLE
Mouse Wheelie is missing button

### ISSUE THREAD

**Issue by LeeroyGarfield** [magicus/ModSettings#7]
The [Mouse Wheelie](https://www.curseforge.com/minecraft/mc-mods/mouse-wheelie) button is missing in the Mod Setting menu. A similar problem also exists in [Flytre Lib](https://www.curseforge.com/minecraft/mc-mods/lib). The former has a Mod Menu button, whereas the latter does not. I'm guessing the latter has its own in-game config menu, preventing your mod from detecting it?

[megane](https://www.curseforge.com/minecraft/mc-mods/megane), a [WTHIT](https://www.curseforge.com/minecraft/mc-mods/wthit) addon, somehow displays two buttons. The menus for "megane" and "megane-runtime" buttons are the same.

So far, I believe that's all the issues I've discovered. I absolutely adore your mod because it makes opening the settings of many mods so much convenient!

**Comment by magicus** [comment]
For Flytre Lib, if there is no button in Mod Menu, then there is nothing I can do. You need to request of the author of the mod to add the Mod Menu API.

For megane, it sounds like the mod is actually bundling a secondary mod, which has it's own configuration. Once again, it's not much I can do about it, but you can ask the mod author to remove the configuration part of the Mod Menu API for megane-runtime, if you believe it is always redundant.

**Comment by LeeroyGarfield** [comment]
> @LeeroyGarfield The Mouse Wheelie issue sounds like a real problem with ModSettings, though. Can you just confirm, so I understand you correctly, that this does indeed have a configure button in Mod Menu, but not in ModSettings?

Yes, Mouse Wheelie does have a configure button in Mod Menu screen, but not in ModSettings screen.
![issue 1](https://user-images.githubusercontent.com/87123836/153400383-dbb05461-c0c9-48e6-a9bf-ffd68406cfdd.png)
![issue 2](https://user-images.githubusercontent.com/87123836/153400431-3bb80f45-a51d-430e-9e24-a36264995acf.png)

I'm assuming because Mouse Wheelie's a little outdated? Its last update was on Nov 27, 2021.

**Comment by magicus** [comment]
The problem with Mouse Wheelie was that it used Tweed to generate the config screen. The Mod Menu API had support for one mod providing config screens for another mod (this very case), but I had not tested my implementation, and that of course implies that it was broken. 

This is now fixed and will be part of the next release of Mod Settings.
