### ISSUE TITLE
NO ISSUE Just want to know how to do

### ISSUE THREAD

**Issue by gamingoninsulin** [magicus/ModSettings#8]
i am just wanted to know ive been following a mod course and i want to launch my mod with this mod as if they where added as real mods if you get what i mean 

like as an dependenties thing when the intelij edtor loads its loads my mod and fabric thats it i want to test it with your mod without installing trough an other application.

greeting insulin ;)

**Comment by magicus** [comment]
@gamingoninsulin I'm not fully sure I understand what you want to achieve, but it sounds like you could google for how to make modpacks. I'm sorry I can't be of any assistance.
