### ISSUE TITLE
Crashed with Minecraft 1.18.2 + Quilt 0.16.00 + Mod Menu 3.21 (Work fine if only use Mod Menu or only Mod Setting but can't use both)

### ISSUE THREAD

**Issue by ardissaps** [magicus/ModSettings#9]

**Comment by ardissaps** [comment]
[X] Minecraft 1.18.2 + Quilt 0.16.00 + Mod Menu 3.21 = Crash

Minecraft 1.18.2 + Quilt 0.16 beta 16 + Mod Menu 3.21 = Work
Minecraft 1.18.2 + Quilt 0.16.00 stabel only = Work
Minecraft 1.18.2 + Quilt 0.16.00 stable + No Modmenu = Work
Minecraft 1.18.2 + Quilt 0.16.00 stable + Mod Menu 3.21 + No ModSettiing = Work

I mean it like game crash if choose all 3 option but work if choose only 2=
Setting+Menu+LatestQuilt=Crash
Setting+MEnu+BetaQuilt=Work
Menu+LatestQuilt= Work
Setting+LatestQuilt = Work

**Comment by magicus** [comment]
Does Minecraft crash at startup if you enable all three mods?

Is Quilt 0.16 beta 16 a beta that preceded Quilt 0.16.00, or a beta for the next version of Quilt? (I.e. is the beta newer or older than the stable version)

**Comment by ardissaps** [comment]
> Does Minecraft crash at startup if you enable all three mods?

Game loads but crashed at main menu.


> Is Quilt 0.16 beta 16 a beta that preceded Quilt 0.16.00, or a beta for the next version of Quilt? (I.e. is the beta newer or older than the stable version)

Idk their it was displayed above the beta version in AT launcher, is it supposed to be newer or older?
Their version look like this when I press change Quilt Version : 

- 0.16.0
- 0.16.0-beta.16 (Current)
- 0.16.0-beta.15
- 0.16.0-beta.14
